
    <script  type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="skins/admin/default/js/bootstrap/bootstrap.js"></script>  
    <script type="text/javascript" src="skins/admin/default/plugins/misc/touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="skins/admin/default/plugins/misc/ios-fix/ios-orientationchange-fix.js"></script>
    <script type="text/javascript" src="skins/admin/default/plugins/forms/validate/jquery.validate.min.js"></script>
    <script type="text/javascript" src="skins/admin/default/plugins/forms/uniform/jquery.uniform.min.js"></script>
    <script type="text/javascript" src="skins/admin/default/js/login.js"></script>

     <script type="text/javascript">
        // document ready function
  
    </script>


    </body>
</html>
