<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{@TITLE@}</title>
    <meta name="author" content="{@AUTHOR@}" />
    <meta name="description" content="{@DECRIPTION@}" />
    <meta name="keywords" content="{@KEYWORDS@}" />
    <meta name="application-name" content="{@APPLICATIONNAME@}" />

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Le styles -->
    <link href="skins/admin/default/css/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="skins/admin/default/css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
    <link href="skins/admin/default/css/supr-theme/jquery.ui.supr.css" rel="stylesheet" type="text/css"/>
    <link href="skins/admin/default/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="skins/admin/default/plugins/forms/uniform/uniform.default.css" type="text/css" rel="stylesheet" />

    <!-- Main stylesheets -->
    <link href="skins/admin/default/css/main.css" rel="stylesheet" type="text/css" /> 
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="skins/admin/default/images/apple-touch-icon-144-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="skins/admin/default/images/apple-touch-icon-114-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="skins/admin/default/images/apple-touch-icon-72-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" href="skins/admin/default/images/apple-touch-icon-57-precomposed.png" />

    </head>