<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Dinamo Elektrik</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <link type="text/css" rel="stylesheet" href="<?php echo DOMAIN; ?>skins/frontend/dinamo/css/select2.css">
        <link type="text/css" rel="stylesheet" href="<?php echo DOMAIN; ?>skins/frontend/dinamo/css/dinamo.css">
        <link type="text/css" rel="stylesheet" href="<?php echo DOMAIN; ?>skins/frontend/dinamo/css/temp-css.css">
        <link type="text/css" rel="stylesheet" href="<?php echo DOMAIN; ?>skins/frontend/dinamo/js/parsley.css">
         <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
            <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <!--[if lt IE 9]>
            <p class="chromeframe">Ne yazık ki <strong>zamanı geçmiş</strong> bir tarayıcı kullanıyorsunuz. Lütfen <a href="http://browsehappy.com/">tarayıcınızı güncelleyin</a> ya da <a href="http://www.google.com/chromeframe/?redirect=true">Google Chrome Frame</a> yükleyerek deneyiminizi artırın.</p>
        <![endif]-->