<footer class="clearfix">
                <div class="social">
                    <div class="container clearfix">
                        <div class="left">
                            <a href="#" class="dinamo-icon-mail"></a>
                            <a href="#" class="dinamo-icon-fb"></a>
                            <a href="#" class="dinamo-icon-tw"></a>
                            <a href="#" class="dinamo-icon-gp"></a>
                            <a href="#" class="dinamo-icon-yt"></a>
                        </div>
                        <a class="btn-black right" href="#">BAYİMİZ OLUN</a>
                    </div>
                </div>
                <nav class="container clearfix">
                    <ul>
                        <li><a href="#">HAKKIMIZDA</a></li>
                        <li><a href="#">HABERLER</a></li>
                        <li><a href="#">BASIN ODASI</a></li>
                        <li><a href="#">SIKÇA SORULAN SORULAR</a></li>
                        <li><a href="#">İLETİŞİM</a></li>
                    </ul>
                </nav>
                <div class="container">
                    <div class="phone">0 800 700 60 50</div>
                    <div class="copy">Dinamo Elektrik bir <span class="dinamo-icon-proper"></span> kuruluşudur.</div>
                    <br clear="all">
                    <br clear="all">
                </div>
            </footer>

        