  
    <!--page spec css block-->
    <!--page spec css block-->
    </body>
</html>
<header>
                <div class="top-menu">
                    <div class="container clearfix">
                        <ul class="customer-type">
                        <?php

                        foreach ($headers as $header) {

                            /**if( $this->url()=='/' && $this->url() == 'bireysel' || $header->getName() =='bireysel' ){
                                echo '<li  class="active" ><a href="'.$this->serverUrl("/cms/".$header->getName()).'">'.$header->getName().'</a></li>';   
                            }
                            
                            else {
                                echo '<li><a href="'.$this->serverUrl("/cms/".$header->getName()).'">'.$header->getName().'</a></li>';
                            }**/
                            if($header->getName() == $activeUrl ){
                                    echo '<li  class="active" ><a href="'.$this->serverUrl("/cms/".$header->getName()).'">'.$header->getValue().'</a></li>'; 
                            }
                            else{
                                echo '<li><a href="'.$this->serverUrl("/cms/".$header->getName()).'">'.$header->getValue().'</a></li>';
                            }
                        }
                        ?>
                            
                        </ul>
                      