  
    <!--page spec css block-->
    <!--page spec css block-->
    </body>
</html>
<header>
                <div class="top-menu">
                    <div class="container clearfix">
                        <ul class="customer-type">
                        <?php

                        foreach ($headers as $header) {

                            if( $this->url()=='/' && $this->url() == 'bireysel' || $header->getName() =='bireysel' ){
                                echo '<li ><a href="'.$this->serverUrl("/cms/".$header->getName()).'">'.$header->getName().'</a></li>';   
                            }
                            
                            else {
                                echo '<li class="active"><a href="'.$this->serverUrl("/cms/".$header->getName()).'">'.$header->getName().'</a></li>';
                            }
                        }
                        ?>
                            
                        </ul>
                        <?php echo $activeUrl;?>