 <nav>
                    <div class="container">
                    <?php 
                    echo '<a href="'.$this->serverUrl("/".$website).'" class="logo" title="Dinamo Elektrik">Dinamo Elektrik</a>';

                    ?>
                        <ul>

                        <?php

                        if($navs){
                            foreach($navs as $nav){
                                echo '<li><a href="'.$this->serverUrl("/".$nav->getUrl()->getName()).'">'.$nav->getName().'</a></li>';    
                            }
                            

                        }
                        else{
                            echo '<li><a href="">İlgili Menu Bulunamadı</a></li>';
                        }



                        ?>
                           
                        </ul>
                        <div class="menu-icon">
                            <ul class="hidden-dd">
                               
                        <?php

                        if($navs){
                            foreach($navs as $nav){
                                echo '<li><a href="'.$this->serverUrl("/".$nav->getUrl()->getName()).'">'.$nav->getName().'</a></li>';    
                            }
                            

                        }
                        else{
                            echo '<li><a href="">İlgili Menu Bulunamadı</a></li>';
                        }



                        ?>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>