<?php

?>
                        <ul class="online-menu clearfix">
                        	<?php 
                        	if($quicks){
                               // $url = getRepository('\Application\Entity\Website')->findBy(array('status'=>'1'));
                               //$test = $this->getUrl();

                            foreach ($quicks as $quick){
                        		//print_r($quick->getName());
                        		echo '<li><a href="'.$this->serverUrl("/cms/".$quick->getUrl()->getName()).'" title="'.$quick->getName().'"><span class="'.$quick->getIcon().'"></span>'.$quick->getName().'</a></li>';
                        	}
                        	}
                        	else{
                        		echo '<li><a href="" title="">Hızlı Kategori Bulunamadı</a></li>';
                        	}
                            //print_r($test);
                        		?>
                         </ul>
                    </div>
                </div>
           
