
                        <ul class="online-menu clearfix">
                             <li><a href="#"><span class="ico-basvur"></span>Hemen Başvur</a></li>
                             <li><a href="#"><span class="ico-basvur"></span>Ödeme Yap</a></li>
                             <li><a href="#"><span class="ico-online"></span>Online İşlem Merkezi</a></li>
                         </ul>
                    </div>
                </div>
<?php var_dump($quicks);?>