<div class="container">
                <div class="cycle-slideshow">
                    <button class="prev" data-cycle-cmd="prev">Prev</button>
                    <div class="cycle-overlay"></div>
                    <img src="<?php echo $this->serverUrl('/skins/frontend/dinamoelektrik/img/slider1.jpg');?>" data-cycle-title="Yaşam tarzınıza uygun elektrik!"
        data-cycle-desc="Dinamo, ihtiyaçlarınıza uygun elektriği hiçbir altyapı değişikliği gerekmeden size sunuyor. ">
                    <img src="http://lorempixel.com/940/500/technics/1/" data-cycle-title="Redwoods"
        data-cycle-desc="Muir Woods National Monument">
                    <img src="http://lorempixel.com/940/500/technics/2/" data-cycle-title="Angel Island"
        data-cycle-desc="San Franscisco Bay">
                    <img src="http://lorempixel.com/940/500/technics/3/" data-cycle-title="Raquette Lake"
        data-cycle-desc="Adirondack State Park">
                    <div class="cycle-pager"></div>
                    <button class="next" data-cycle-cmd="next">Next</button>
                </div>
                <hr>
            </div>